// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdCF6Ez8blsUqBQm81IPWF6pSjk_peRMc',
    appId: '1:390623553844:web:06714681d3692931dd5d61',
    messagingSenderId: '390623553844',
    projectId: 'chatmessengerapp-63c77',
    authDomain: 'chatmessengerapp-63c77.firebaseapp.com',
    storageBucket: 'chatmessengerapp-63c77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdjS_8B2V1JLV_8Ch0ipEeYuiuDITHJmQ',
    appId: '1:390623553844:android:3d4e72afeb03f2b6dd5d61',
    messagingSenderId: '390623553844',
    projectId: 'chatmessengerapp-63c77',
    storageBucket: 'chatmessengerapp-63c77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqWanYWY2IfD4isaBlwnd3PWxUwJylQ88',
    appId: '1:390623553844:ios:15c4ebc0fe09ef4add5d61',
    messagingSenderId: '390623553844',
    projectId: 'chatmessengerapp-63c77',
    storageBucket: 'chatmessengerapp-63c77.appspot.com',
    iosClientId: '390623553844-697qac5pkm83rdj437qt0hvebjlve6hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqWanYWY2IfD4isaBlwnd3PWxUwJylQ88',
    appId: '1:390623553844:ios:041696b419d3aa50dd5d61',
    messagingSenderId: '390623553844',
    projectId: 'chatmessengerapp-63c77',
    storageBucket: 'chatmessengerapp-63c77.appspot.com',
    iosClientId: '390623553844-4e7n3qfa6k2o7952qfi28epq0g6k1hm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMessengerApp.RunnerTests',
  );
}
